package com.mrh.genshincharacter.model

object CharactersData {
    val characters = listOf(
        GenshinCharacterItem(
            "1",
            "Candace",
            "Sumeru",
            "Polearm",
            "Hydro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/candace.webp"
        ),
        GenshinCharacterItem(
            "2",
            "Chongyun",
            "Liyue",
            "Greatsword",
            "Cryo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/chongyun.webp"
        ),
        GenshinCharacterItem(
            "3",
            "Collei",
            "Sumeru",
            "Bow",
            "Dendro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/collei.webp"
        ),
        GenshinCharacterItem(
            "4",
            "Cyno",
            "Sumeru",
            "Polearm",
            "Electro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/cyno.webp"
        ),
        GenshinCharacterItem(
            "5",
            "Dehya",
            "Sumeru",
            "Greatsword",
            "Pyro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/dehya.webp"
        ),
        GenshinCharacterItem(
            "6",
            "Diona",
            "Mondstadt",
            "bow",
            "Cryo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/diona.webp"
        ),
        GenshinCharacterItem(
            "7",
            "Dori",
            "Sumeru",
            "Greatsword",
            "Electro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/dori.webp"
        ),
        GenshinCharacterItem(
            "8",
            "Eula",
            "Mondstadt",
            "Greatsword",
            "Cryo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/eula.webp"
        ),
        GenshinCharacterItem(
            "9",
            "Faruzan",
            "Sumeru",
            "Bow",
            "Anemo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/faruzan.webp"
        ),
        GenshinCharacterItem(
            "10",
            "Fischl",
            "Mondstadt",
            "Bow",
            "Electro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/fischl.webp"
        ),
        GenshinCharacterItem(
            "11",
            "Ganyu",
            "Liyue",
            "Bow",
            "Cryo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/ganyu.webp"
        ),
        GenshinCharacterItem(
            "12",
            "Gorou",
            "Inazuma",
            "Bow",
            "Geo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/gorou.webp"
        ),
        GenshinCharacterItem(
            "13",
            "Hutao",
            "Liyue",
            "Polearm",
            "Pyro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/hutao.webp"
        ),
        GenshinCharacterItem(
            "14",
            "Jean",
            "Mondstadt",
            "Sword",
            "Anemo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/jean.webp"
        ),
        GenshinCharacterItem(
            "15",
            "Kaeya",
            "Mondstadt",
            "Sword",
            "Cryo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/kaeya.webp"
        ),
        GenshinCharacterItem(
            "16",
            "Kamisato Ayaka",
            "Inazuma",
            "Sword",
            "Cryo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/kamisatoayaka.webp"
        ),
        GenshinCharacterItem(
            "17",
            "Kaveh",
            "Sumeru",
            "Greatsword",
            "Dendro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/kaveh.webp"
        ),
        GenshinCharacterItem(
            "18",
            "Kazuha",
            "Inazuma",
            "Sword",
            "Anemo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/kazuha.webp"
        ),
        GenshinCharacterItem(
            "19",
            "Keqing",
            "Liyue",
            "Sword",
            "Electro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/keqing.webp"
        ),
        GenshinCharacterItem(
            "20",
            "Kirara",
            "Inazuma",
            "Sword",
            "Dendro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/kirara.webp"
        ),
        GenshinCharacterItem(
            "21",
            "Klee",
            "Mondstadt",
            "Catalyst",
            "Pyro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/klee.webp"
        ),
        GenshinCharacterItem(
            "22",
            "Kujou Sara",
            "Inazuma",
            "Bow",
            "Electro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/kujousara.webp"
        ),
        GenshinCharacterItem(
            "23",
            "Kuki Shinobu",
            "Inazuma",
            "Sword",
            "Electro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/kukishinobu.webp"
        ),
        GenshinCharacterItem(
            "24",
            "Layla",
            "Sumeru",
            "Sword",
            "Cryo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/layla.webp"
        ),
        GenshinCharacterItem(
            "25",
            "Lisa",
            "Mondstadt",
            "Catalyst",
            "Electro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/lisa.webp"
        ),
        GenshinCharacterItem(
            "26",
            "Mika",
            "Mondstadt",
            "Polearm",
            "Cryo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/mika.webp"
        ),
        GenshinCharacterItem(
            "27",
            "Nahida",
            "Sumeru",
            "Catalyst",
            "Dendro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/nahida.webp"
        ),
        GenshinCharacterItem(
            "28",
            "Nilou",
            "Sumeru",
            "Sword",
            "Hydro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/nilou.webp"
        ),
        GenshinCharacterItem(
            "29",
            "Ningguang",
            "Liyue",
            "Catalyst",
            "Geo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/ningguang.webp"
        ),
        GenshinCharacterItem(
            "30",
            "Noelle",
            "Mondstadt",
            "Greatsword",
            "Geo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/noelle.webp"
        ),
        GenshinCharacterItem(
            "31",
            "Qiqi",
            "Liyue",
            "Sword",
            "Cryo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/qiqi.webp"
        ),
        GenshinCharacterItem(
            "32",
            "Raiden Shogun",
            "Inazuma",
            "Polearm",
            "Electro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/raidenshogun.webp"
        ),
        GenshinCharacterItem(
            "33",
            "Razor",
            "Mondstadt",
            "Greatsword",
            "Electro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/razor.webp"
        ),
        GenshinCharacterItem(
            "34",
            "Rosaria",
            "Mondstadt",
            "Polearm",
            "Cryo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/rosaria.webp"
        ),
        GenshinCharacterItem(
            "35",
            "Sangonomiya Kokomi",
            "Inazuma",
            "Catalyst",
            "Hydro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/sangonomiyakokomi.webp"
        ),
        GenshinCharacterItem(
            "36",
            "Sayu",
            "Inazuma",
            "Greatsword",
            "Anemo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/sayu.webp"
        ),
        GenshinCharacterItem(
            "37",
            "Shenhe",
            "Liyue",
            "Polearm",
            "Cryo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/shenhe.webp"
        ),
        GenshinCharacterItem(
            "38",
            "Shikanoin Heizou",
            "Inazuma",
            "Catalyst",
            "Anemo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/shikanoinheizou.webp"
        ),
        GenshinCharacterItem(
            "39",
            "Sucrose",
            "Mondstadt",
            "Catalyst",
            "Anemo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/sucrose.webp"
        ),
        GenshinCharacterItem(
            "40",
            "Tartaglia",
            "Snezhnaya",
            "Bow",
            "Hydro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/tartagliachilde.webp"
        ),
        GenshinCharacterItem(
            "41",
            "Thoma",
            "Inazuma",
            "Polearm",
            "Pyro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/thoma.webp"
        ),
        GenshinCharacterItem(
            "42",
            "Tighnari",
            "Sumeru",
            "Bow",
            "Dendro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/tighnari.webp"
        ),
        GenshinCharacterItem(
            "43",
            "Twin",
            "Outlander",
            "Sword",
            "Multiple Element",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/twin.webp"
        ),
        GenshinCharacterItem(
            "44",
            "Venti",
            "Mondstadt",
            "Bow",
            "Anemo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/venti.webp"
        ),
        GenshinCharacterItem(
            "45",
            "Wanderer",
            "Inazuma",
            "Catalyst",
            "Anemo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/wanderer.webp"
        ),
        GenshinCharacterItem(
            "46",
            "Xiangling",
            "Liyue",
            "Polearm",
            "Pyro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/xiangling.webp"
        ),
        GenshinCharacterItem(
            "47",
            "Xiao",
            "Liyue",
            "Polearm",
            "Anemo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/xiao.webp"
        ),
        GenshinCharacterItem(
            "48",
            "Xingqiu",
            "Liyue",
            "Sword",
            "Hydro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/xingqiu.webp"
        ),
        GenshinCharacterItem(
            "49",
            "Xinyan",
            "Liyue",
            "Greatsword",
            "Pyro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/xinyan.webp"
        ),
        GenshinCharacterItem(
            "50",
            "Yaemiko",
            "Inazuma",
            "Catalyst",
            "Electro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/yaemiko.webp"
        ),
        GenshinCharacterItem(
            "51",
            "Yanfei",
            "Liyue",
            "Catalyst",
            "Pyro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/yanfei.webp"
        ),
        GenshinCharacterItem(
            "52",
            "Yaoyao",
            "Liyue",
            "Polearm",
            "Dendro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/yaoyao.webp"
        ),
        GenshinCharacterItem(
            "53",
            "Yelan",
            "Liyue",
            "Bow",
            "Hydro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/yelan.webp"
        ),
        GenshinCharacterItem(
            "54",
            "Yoimiya",
            "Inazuma",
            "Bow",
            "Pyro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/yoimiya.webp"
        ),
        GenshinCharacterItem(
            "55",
            "Yunjin",
            "Liyue",
            "Polearm",
            "Geo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/yunjin.webp"
        ),
        GenshinCharacterItem(
            "56",
            "Zhongli",
            "Liyue",
            "Polearm",
            "Geo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/zhongli.webp"
        ),
        GenshinCharacterItem(
            "57",
            "Albedo",
            "Mondstadt",
            "Sword",
            "Geo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/albedo.webp"
        ),
        GenshinCharacterItem(
            "58",
            "Alhaitham",
            "Sumeru",
            "Sword",
            "Dendro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/alhaitham.webp"
        ),
        GenshinCharacterItem(
            "59",
            "Aloy",
            "Outlander",
            "Bow",
            "Cryo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/aloy.webp"
        ),
        GenshinCharacterItem(
            "60",
            "Amber",
            "Mondstadt",
            "Bow",
            "Pyro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/amber.webp"
        ),
        GenshinCharacterItem(
            "61",
            "Arataki Itto",
            "Inazuma",
            "Greatsword",
            "geo",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/AratakiItto.webp"
        ),
        GenshinCharacterItem(
            "62",
            "Kamisato Ayato",
            "Inazuma",
            "Sword",
            "Hydro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/ayatokamisato.webp"
        ),
        GenshinCharacterItem(
            "63",
            "Baizhu",
            "Liyue",
            "Catalyst",
            "Dendro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/baizhu.webp"
        ),
        GenshinCharacterItem(
            "64",
            "Barbara",
            "Mondstadt",
            "Catalyst",
            "Hydro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/barbara.webp"
        ),
        GenshinCharacterItem(
            "65",
            "Beidou",
            "Liyue",
            "Greatsword",
            "Electro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/beidou.webp"
        ),
        GenshinCharacterItem(
            "66",
            "Bennett",
            "Mondstadt",
            "Sword",
            "Pyro",
            "https://sibisa.sman1rawamerta.sch.id/assets/genshin/bennett.webp"
        )
    )
}